-- v2 语义层元数据表
-- 执行角色：embed_app，连接数据库：embedding_store

CREATE SCHEMA IF NOT EXISTS governance;

CREATE TABLE IF NOT EXISTS governance.table_metadata (
    table_name varchar(128) PRIMARY KEY,
    business_meaning text NOT NULL,
    grain text NOT NULL DEFAULT '未指定',
    is_active boolean NOT NULL DEFAULT true,
    embedding vector(1024),
    embedding_model varchar(128),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS governance.column_metadata (
    table_name varchar(128) NOT NULL,
    column_name varchar(128) NOT NULL,
    data_type varchar(128) NOT NULL,
    business_meaning text NOT NULL,
    sensitive_level varchar(16) NOT NULL DEFAULT 'public'
        CHECK (sensitive_level IN ('public', 'masked', 'restricted')),
    allowed_roles text[] NOT NULL DEFAULT ARRAY['shop_ro']::text[],
    embedding vector(1024),
    embedding_model varchar(128),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (table_name, column_name)
);

CREATE TABLE IF NOT EXISTS governance.metric_metadata (
    metric_code varchar(64) PRIMARY KEY,
    metric_name varchar(128) NOT NULL,
    definition text NOT NULL,
    calculation_sql_template text NOT NULL,
    unit varchar(32) NOT NULL,
    grain varchar(64) NOT NULL,
    embedding vector(1024),
    embedding_model varchar(128),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS governance.query_example (
    example_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    question text NOT NULL,
    sql_text text NOT NULL,
    tables_used text[] NOT NULL DEFAULT ARRAY[]::text[],
    embedding vector(1024),
    embedding_model varchar(128),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_table_metadata_embedding
    ON governance.table_metadata USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_column_metadata_embedding
    ON governance.column_metadata USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_metric_metadata_embedding
    ON governance.metric_metadata USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_query_example_embedding
    ON governance.query_example USING hnsw (embedding vector_cosine_ops);

-- 固化 shop_dw 表与字段元数据（PostgreSQL database 之间不能跨库查询 catalog）
INSERT INTO governance.table_metadata (table_name, business_meaning, grain) VALUES
    ('dim_category', '商品类目层级维度', '一行一个业务维度成员'),
    ('dim_channel', '订单与行为事件所属的渠道维度', '一行一个业务维度成员'),
    ('dim_date', '日期维度，用于订单、支付、退款和事件按日期分析', '一行一个业务维度成员'),
    ('dim_merchant', '平台内商家店铺维度', '一行一个业务维度成员'),
    ('dim_payment_method', '微信支付、支付宝等支付方式维度', '一行一个业务维度成员'),
    ('dim_product', '商品 SKU 维度', '一行一个业务维度成员'),
    ('dim_promotion', '满减、折扣、优惠券等促销活动维度', '一行一个业务维度成员'),
    ('dim_region', '国家省市区四级地区维度', '一行一个业务维度成员'),
    ('dim_user', '购物 App 注册用户维度', '一行一个业务维度成员'),
    ('fact_app_event', 'App 行为事件事实表，记录浏览、搜索、加购、支付等行为', '一行一笔业务记录'),
    ('fact_logistics_order', '一行一个物流运单，记录订单发货的运单与当前状态', '一行一笔业务记录'),
    ('fact_logistics_trace', '物流状态流水，一行一次发货、运输或签收等状态更新', '一行一次物流状态变更'),
    ('fact_order', '手机购物 App 订单头事实表', '一行一笔业务记录'),
    ('fact_order_item', '订单明细事实表，含订单头状态、收货信息、商品快照与物流关联', '一行一个订单商品明细'),
    ('fact_payment', '支付事实表，一行一次支付交易', '一行一笔业务记录'),
    ('fact_refund', '退款事实表，支持整单退款或按明细退款', '一行一笔业务记录')
ON CONFLICT (table_name) DO UPDATE SET
    business_meaning = EXCLUDED.business_meaning,
    grain = EXCLUDED.grain,
    updated_at = now();

INSERT INTO governance.column_metadata (table_name, column_name, data_type, business_meaning, sensitive_level, allowed_roles) VALUES
    ('dim_category', 'category_key', 'bigint', 'category_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_category', 'category_code', 'character varying', 'category_code', 'public', ARRAY['shop_ro']::text[]),
    ('dim_category', 'category_name', 'character varying', 'category_name', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_category', 'parent_category_key', 'bigint', 'parent_category_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_category', 'category_level', 'smallint', 'category_level', 'public', ARRAY['shop_ro']::text[]),
    ('dim_category', 'sort_no', 'integer', 'sort_no', 'public', ARRAY['shop_ro']::text[]),
    ('dim_category', 'status', 'boolean', 'status', 'public', ARRAY['shop_ro']::text[]),
    ('dim_category', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'channel_key', 'bigint', 'channel_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'channel_code', 'character varying', 'channel_code', 'public', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'channel_name', 'character varying', 'channel_name', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'channel_type', 'character varying', 'channel_type', 'public', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'platform', 'character varying', 'platform', 'public', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'device_platform', 'character varying', 'device_platform', 'public', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'is_paid', 'boolean', 'is_paid', 'public', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'status', 'boolean', 'status', 'public', ARRAY['shop_ro']::text[]),
    ('dim_channel', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'date_key', 'integer', 'date_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'calendar_date', 'date', 'calendar_date', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'year', 'smallint', 'year', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'quarter', 'smallint', 'quarter', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'month', 'smallint', 'month', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'day', 'smallint', 'day', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'week_of_year', 'smallint', 'week_of_year', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'day_of_week', 'smallint', 'day_of_week', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'day_name_cn', 'character varying', 'day_name_cn', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_date', 'is_weekend', 'boolean', 'is_weekend', 'public', ARRAY['shop_ro']::text[]),
    ('dim_date', 'is_holiday', 'boolean', 'is_holiday', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'merchant_key', 'bigint', 'merchant_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'merchant_id', 'character varying', 'merchant_id', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'merchant_name', 'character varying', 'merchant_name', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'merchant_type', 'character varying', 'merchant_type', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'merchant_level', 'character varying', 'merchant_level', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'region_key', 'bigint', 'region_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'service_score', 'numeric', 'service_score', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'status', 'boolean', 'status', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'opened_at', 'date', 'opened_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_merchant', 'updated_at', 'timestamp with time zone', 'updated_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_payment_method', 'payment_method_key', 'bigint', 'payment_method_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_payment_method', 'method_code', 'character varying', 'method_code', 'public', ARRAY['shop_ro']::text[]),
    ('dim_payment_method', 'method_name', 'character varying', 'method_name', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_payment_method', 'provider', 'character varying', 'provider', 'public', ARRAY['shop_ro']::text[]),
    ('dim_payment_method', 'supported_platform', 'character varying', 'supported_platform', 'public', ARRAY['shop_ro']::text[]),
    ('dim_payment_method', 'is_active', 'boolean', 'is_active', 'public', ARRAY['shop_ro']::text[]),
    ('dim_payment_method', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'product_key', 'bigint', 'product_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'product_id', 'character varying', 'product_id', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'sku_code', 'character varying', 'sku_code', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'product_name', 'character varying', 'product_name', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_product', 'brand', 'character varying', 'brand', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'spec', 'character varying', 'spec', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'category_key', 'bigint', 'category_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'merchant_key', 'bigint', 'merchant_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'reference_price', 'numeric', 'reference_price', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'cost_price', 'numeric', 'cost_price', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'shelf_status', 'character varying', 'shelf_status', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'on_shelf_at', 'timestamp with time zone', 'on_shelf_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'off_shelf_at', 'timestamp with time zone', 'off_shelf_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_product', 'updated_at', 'timestamp with time zone', 'updated_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'promotion_key', 'bigint', 'promotion_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'promotion_id', 'character varying', 'promotion_id', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'promotion_name', 'character varying', 'promotion_name', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'promotion_type', 'character varying', 'promotion_type', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'discount_type', 'character varying', 'discount_type', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'discount_value', 'numeric', 'discount_value', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'start_at', 'timestamp with time zone', 'start_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'end_at', 'timestamp with time zone', 'end_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'status', 'character varying', 'status', 'public', ARRAY['shop_ro']::text[]),
    ('dim_promotion', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_region', 'region_key', 'bigint', 'region_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_region', 'region_code', 'character varying', 'region_code', 'public', ARRAY['shop_ro']::text[]),
    ('dim_region', 'region_name', 'character varying', 'region_name', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_region', 'region_type', 'character varying', 'region_type', 'public', ARRAY['shop_ro']::text[]),
    ('dim_region', 'parent_region_key', 'bigint', 'parent_region_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_region', 'level', 'smallint', 'level', 'public', ARRAY['shop_ro']::text[]),
    ('dim_region', 'region_path', 'character varying', 'region_path', 'public', ARRAY['shop_ro']::text[]),
    ('dim_region', 'status', 'boolean', 'status', 'public', ARRAY['shop_ro']::text[]),
    ('dim_region', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'user_key', 'bigint', 'user_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'user_id', 'character varying', 'user_id', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'nickname_masked', 'character varying', 'nickname_masked', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_user', 'phone_masked', 'character varying', 'phone_masked', 'masked', ARRAY['shop_ro']::text[]),
    ('dim_user', 'gender_code', 'character varying', 'gender_code', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'age_group', 'character varying', 'age_group', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'member_level', 'character varying', 'member_level', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'default_region_key', 'bigint', 'default_region_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'register_channel_key', 'bigint', 'register_channel_key', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'registration_date', 'date', 'registration_date', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'status', 'character varying', 'status', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('dim_user', 'updated_at', 'timestamp with time zone', 'updated_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'event_key', 'bigint', 'event_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'event_id', 'character varying', 'event_id', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'date_key', 'integer', 'date_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'user_key', 'bigint', 'user_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'channel_key', 'bigint', 'channel_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'region_key', 'bigint', 'region_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'product_key', 'bigint', 'product_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'order_key', 'bigint', 'order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'session_id', 'character varying', 'session_id', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'page_code', 'character varying', 'page_code', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'event_type', 'character varying', 'event_type', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'event_time', 'timestamp with time zone', 'event_time', 'public', ARRAY['shop_ro']::text[]),
    ('fact_app_event', 'payload', 'jsonb', 'payload', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'logistics_order_key', 'bigint', 'logistics_order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'logistics_no', 'character varying', 'logistics_no', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'order_key', 'bigint', 'order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'logistics_company', 'character varying', 'logistics_company', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'current_status', 'character varying', 'current_status', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'current_status_time', 'timestamp with time zone', 'current_status_time', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'shipped_at', 'timestamp with time zone', 'shipped_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'signed_at', 'timestamp with time zone', 'signed_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'expected_arrival_at', 'timestamp with time zone', 'expected_arrival_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_order', 'updated_at', 'timestamp with time zone', 'updated_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'logistics_trace_key', 'bigint', 'logistics_trace_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'logistics_order_key', 'bigint', 'logistics_order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'order_key', 'bigint', 'order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'trace_status', 'character varying', 'trace_status', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'trace_status_cn', 'character varying', 'trace_status_cn', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'trace_time', 'timestamp with time zone', 'trace_time', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'location_name', 'character varying', 'location_name', 'masked', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'operator_name', 'character varying', 'operator_name', 'masked', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'signed_name', 'character varying', 'signed_name', 'masked', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'trace_description', 'character varying', 'trace_description', 'public', ARRAY['shop_ro']::text[]),
    ('fact_logistics_trace', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'order_key', 'bigint', 'order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'order_no', 'character varying', 'order_no', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'date_key', 'integer', 'date_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'user_key', 'bigint', 'user_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'channel_key', 'bigint', 'channel_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'shipping_region_key', 'bigint', 'shipping_region_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'promotion_key', 'bigint', 'promotion_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'order_status', 'character varying', 'order_status', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'is_shipped', 'boolean', 'is_shipped', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'goods_amount', 'numeric', 'goods_amount', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'discount_amount', 'numeric', 'discount_amount', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'freight_amount', 'numeric', 'freight_amount', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'pay_amount', 'numeric', 'pay_amount', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'item_count', 'integer', 'item_count', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'order_created_at', 'timestamp with time zone', 'order_created_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'paid_at', 'timestamp with time zone', 'paid_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'received_at', 'timestamp with time zone', 'received_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'cancelled_at', 'timestamp with time zone', 'cancelled_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'completed_at', 'timestamp with time zone', 'completed_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order', 'updated_at', 'timestamp with time zone', 'updated_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'order_item_key', 'bigint', 'order_item_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'order_key', 'bigint', 'order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'order_item_no', 'character varying', 'order_item_no', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'date_key', 'integer', 'date_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'product_key', 'bigint', 'product_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'merchant_key', 'bigint', 'merchant_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'promotion_key', 'bigint', 'promotion_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'quantity', 'integer', 'quantity', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'unit_price', 'numeric', 'unit_price', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'discount_amount', 'numeric', 'discount_amount', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'item_amount', 'numeric', 'item_amount', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'item_status', 'character varying', 'item_status', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'order_status', 'character varying', 'order_status', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'paid_at', 'timestamp with time zone', 'paid_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'received_at', 'timestamp with time zone', 'received_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'is_shipped', 'boolean', 'is_shipped', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'shipping_region_key', 'bigint', 'shipping_region_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'shipping_province_name', 'character varying', 'shipping_province_name', 'masked', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'shipping_city_name', 'character varying', 'shipping_city_name', 'masked', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'shipping_district_name', 'character varying', 'shipping_district_name', 'masked', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'shipping_detail_address', 'character varying', 'shipping_detail_address', 'restricted', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'recipient_name', 'character varying', 'recipient_name', 'restricted', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'recipient_phone', 'character varying', 'recipient_phone', 'restricted', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'product_name_snapshot', 'character varying', 'product_name_snapshot', 'masked', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'category_path_snapshot', 'character varying', 'category_path_snapshot', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'logistics_order_key', 'bigint', 'logistics_order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'created_at', 'timestamp with time zone', 'created_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_order_item', 'updated_at', 'timestamp with time zone', 'updated_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'payment_key', 'bigint', 'payment_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'payment_no', 'character varying', 'payment_no', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'order_key', 'bigint', 'order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'date_key', 'integer', 'date_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'payment_method_key', 'bigint', 'payment_method_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'pay_amount', 'numeric', 'pay_amount', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'payment_status', 'character varying', 'payment_status', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'payment_started_at', 'timestamp with time zone', 'payment_started_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'payment_finished_at', 'timestamp with time zone', 'payment_finished_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'payment_trade_no', 'character varying', 'payment_trade_no', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'error_code', 'character varying', 'error_code', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'error_message', 'text', 'error_message', 'public', ARRAY['shop_ro']::text[]),
    ('fact_payment', 'updated_at', 'timestamp with time zone', 'updated_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'refund_key', 'bigint', 'refund_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'refund_no', 'character varying', 'refund_no', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'order_key', 'bigint', 'order_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'order_item_key', 'bigint', 'order_item_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'payment_key', 'bigint', 'payment_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'date_key', 'integer', 'date_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'user_key', 'bigint', 'user_key', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'refund_type', 'character varying', 'refund_type', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'refund_reason_code', 'character varying', 'refund_reason_code', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'refund_reason', 'text', 'refund_reason', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'refund_amount', 'numeric', 'refund_amount', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'refund_status', 'character varying', 'refund_status', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'applied_at', 'timestamp with time zone', 'applied_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'finished_at', 'timestamp with time zone', 'finished_at', 'public', ARRAY['shop_ro']::text[]),
    ('fact_refund', 'updated_at', 'timestamp with time zone', 'updated_at', 'public', ARRAY['shop_ro']::text[]);

-- 初始化常用指标口径
INSERT INTO governance.metric_metadata (
    metric_code, metric_name, definition, calculation_sql_template, unit, grain
) VALUES
    ('order_amount', '订单商品金额', '订单明细的商品销售金额合计', 'SUM(item_amount)', '元', '可按日期、品类、渠道、商家、地区聚合'),
    ('pay_amount', '支付金额', '支付成功金额合计', 'SUM(pay_amount)', '元', '可按日期、渠道、支付方式聚合'),
    ('refund_amount', '退款金额', '退款金额合计', 'SUM(refund_amount)', '元', '可按日期、品类、商家聚合'),
    ('order_count', '订单量', '去重订单数量', 'COUNT(DISTINCT order_key)', '单', '可按日期、品类、渠道、地区聚合'),
    ('refund_rate', '退款率', '退款金额除以支付金额', 'SUM(refund_amount) / NULLIF(SUM(pay_amount), 0) * 100', '百分比', '可按日期聚合')
ON CONFLICT (metric_code) DO UPDATE SET
    metric_name = EXCLUDED.metric_name,
    definition = EXCLUDED.definition,
    calculation_sql_template = EXCLUDED.calculation_sql_template,
    unit = EXCLUDED.unit,
    grain = EXCLUDED.grain,
    updated_at = now();

-- 初始化常见查询示例
INSERT INTO governance.query_example (question, sql_text, tables_used)
SELECT * FROM (VALUES
    ('2025年11月各品类的订单金额排名情况', 'SELECT d.category_name, SUM(oi.item_amount) AS order_amount FROM fact_order_item oi JOIN dim_product p ON oi.product_key = p.product_key JOIN dim_category d ON p.category_key = d.category_key JOIN dim_date dt ON oi.date_key = dt.date_key WHERE dt.calendar_date BETWEEN DATE ''2025-11-01'' AND DATE ''2025-11-30'' GROUP BY d.category_name ORDER BY order_amount DESC;', ARRAY['fact_order_item', 'dim_product', 'dim_category', 'dim_date']::text[]),
    ('2025年618期间各渠道的订单量和支付金额统计', 'SELECT c.channel_name, COUNT(DISTINCT o.order_key) AS order_count, SUM(o.pay_amount) AS pay_amount FROM fact_order o JOIN dim_channel c ON o.channel_key = c.channel_key JOIN dim_date dt ON o.date_key = dt.date_key WHERE dt.calendar_date BETWEEN DATE ''2025-06-01'' AND DATE ''2025-06-18'' GROUP BY c.channel_name ORDER BY pay_amount DESC;', ARRAY['fact_order', 'dim_channel', 'dim_date']::text[]),
    ('2026年1-8月每月的退款金额和退款率趋势', 'WITH refund_monthly AS (SELECT TO_CHAR(dt.calendar_date, ''YYYY-MM'') AS year_month, SUM(r.refund_amount) AS refund_amount FROM fact_refund r JOIN dim_date dt ON r.date_key = dt.date_key WHERE dt.calendar_date BETWEEN DATE ''2026-01-01'' AND DATE ''2026-08-31'' GROUP BY year_month), payment_monthly AS (SELECT TO_CHAR(dt.calendar_date, ''YYYY-MM'') AS year_month, SUM(p.pay_amount) AS pay_amount FROM fact_payment p JOIN dim_date dt ON p.date_key = dt.date_key WHERE dt.calendar_date BETWEEN DATE ''2026-01-01'' AND DATE ''2026-08-31'' GROUP BY year_month) SELECT r.year_month, r.refund_amount, ROUND(r.refund_amount / NULLIF(p.pay_amount, 0) * 100, 2) AS refund_rate FROM refund_monthly r JOIN payment_monthly p ON r.year_month = p.year_month ORDER BY r.year_month;', ARRAY['fact_refund', 'fact_payment', 'dim_date']::text[]),
    ('哪些省份的订单量最高', 'SELECT oi.shipping_province_name AS province, COUNT(DISTINCT o.order_key) AS order_count FROM fact_order o JOIN fact_order_item oi ON o.order_key = oi.order_key GROUP BY oi.shipping_province_name ORDER BY order_count DESC;', ARRAY['fact_order', 'fact_order_item']::text[])
) AS seed(question, sql_text, tables_used)
WHERE NOT EXISTS (
    SELECT 1 FROM governance.query_example q WHERE q.question = seed.question
);

